background #2E2E2E
foreground #FFF0F5

cursor #FFF0F5
cursor_text_color #2E2E2E

selection_background #FFF0F5
selection_foreground #2E2E2E

# htop, dull black
color0 #424242
# light black
color8 #229799

# git status
color1 #E69DB8
# light red
color9 #E69DB8

# script file
color2 #BBD8A3
# light green
color10 #BBD8A3

# yellow
color3 #FFF0BD
# light yellow
color11 #FFF0BD

# directory
color4 #03A791
# blue
color12 #03A791

# .png
color5 #73C7C7
# light magenta
color13 #73C7C7

# ln -s
color6 #C4D9FF
# light cyan
color14 #C4D9FF

# dull white
color7 #FDFAF6
# bright white
color15 #FDFAF6

