default:
    @just --list

# 重置 obsidian
obsidian-in:
    @rm -rfv ~/Documents/notes/.obsidian
    @tar -zxvf /data/bak/reset/obsidian_config_bak.tar.gz -C ~/Documents/notes
    @echo "✅ obsidian 重置完成"

# obsidian 备份时注意: 先恢复跟踪 -> data 重置 -> 改配置 -> git 提交 -> data 备份 -> 最后忽略跟踪

# 备份 obsidian
obsidian-bak:
    @rm -rfv /data/bak/reset/obsidian_config_bak.tar.gz
    @tar -zcvf /data/bak/reset/obsidian_config_bak.tar.gz -C ~/Documents/notes .obsidian
    @echo "✅ obsidian 备份完成"

# 重新安装 nekoray
nekoray-in:
    @pkill -15 nekoray || echo "nekoray 未运行，跳过终止步骤"
    @rm -rfv /opt/soft/nekoray
    @tar -zxvf /data/bak/reset/nekoray.tar.gz -C /opt/soft
    @echo "✅ nekoray 已重新安装"

# 备份 nekoray
nekoray-bak:
    @pkill -15 nekoray || echo "nekoray 未运行，跳过终止步骤"
    @rm -rfv /data/bak/reset/nekoray.tar.gz
    @tar -zcvf /data/bak/reset/nekoray.tar.gz -C /opt/soft nekoray
    @echo "✅ nekoray 备份完成"

# 拉取新的 cookie
# cookie:
#     @rm -rfv /data/bak/reset/cookies.txt
#     @mv ~/Downloads/cookies.txt /data/bak/reset/
#     @chmod 600 /data/bak/reset/cookies.txt
#     @echo "🍪 cookie 拉取成功"
